nameOverride: ""
fullnameOverride: ""

api:
  image:
    repository: 723255503624.dkr.ecr.us-east-1.amazonaws.com/ship-it-api
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

  secretName: "ship-it"

  nodePort: 31901
  containerPort: 80
  servicePort: 80

syncd:
  image:
    repository: 723255503624.dkr.ecr.us-east-1.amazonaws.com/ship-it-syncd
    tag: latest
    pullPolicy: IfNotPresent

  ecrQueue: ship-it-ecr.fifo
  githubQueue: ship-it-github.fifo

  namespace: default

  operationsRepository: miranda

  releaseName: ship-it-registry
  registryChartPath: k8s/charts/components/ship-it-registry

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
      limits:
        cpu: 1
        memory: 1Gi

github:
  org: "Wattpad"
  token: "foobarbaz"

awsRegion: "us-east-1"

sslCertPath: "/etc/ssl/certs/ca-certificates.crt"
