nameOverride: ""
fullnameOverride: ""

awsRegion: us-east-1
sslCertPath: /etc/ssl/certs/ca-bundle.crt
tillerAddress: tiller-deploy.kube-system.svc.cluster.local:44134

iamRoleArn: arn:aws:iam::723255503624:role/ship-it-prod-v4

externalSecretName: prod-v3/default/ship-it
existingSecretName: ship-it

useDogstatsdHostIP: true

api:
  image:
    repository: 723255503624.dkr.ecr.us-east-1.amazonaws.com/ship-it-api
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

  nodePort: 31901
  containerPort: 80
  servicePort: 80

operator:
  image:
    repository: 723255503624.dkr.ecr.us-east-1.amazonaws.com/ship-it-operator
    tag: ae101faf94f89e8410726a9fe261eee24e79eac2
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 256Mi

  gracePeriod: 10s
  metricsPort: 8080
  namespace: wattpad-system
  enableLeaderElection: false

syncd:
  annotations:
    reloader.stakater.com/auto: "true"

  image:
    repository: 723255503624.dkr.ecr.us-east-1.amazonaws.com/ship-it-syncd
    tag: latest
    pullPolicy: IfNotPresent

  ecrQueue: ship-it-ecr.fifo
  githubQueue: ship-it-github.fifo

  namespace: wattpad-system

  githubOrg: Wattpad
  operationsRepository: miranda

  releaseName: ship-it-registry
  releaseBranch: master
  registryChartPath: k8s/charts/components/ship-it-registry

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
