nameOverride: ""
fullnameOverride: ""

awsRegion: us-east-1

# SSL Certs path for EKS Linux AMI
sslCertPath: /etc/ssl/certs/ca-bundle.crt

# Tiller service's cluster address
tillerAddress: tiller-deploy.kube-system.svc.cluster.local:44134

# IAM role used by ship-it's ServiceAccount
iamRoleArn: ""

# Optional: The desired name of ship-it's ExternalSecret. If no name is provided
# an ExternalSecret will not be created.
externalSecretName: ""

# Optional: The name of an existing Secret which is used to populate the syncd
# deployment's pod env.
existingSecretName: ""

# Whether to use the host IP as the DOGSTATSD_HOST to send metrics to. Should be
# set to true if using a dd-agent Daemonset.
useDogstatsdHostIP: true

api:
  image:
    repository: wattpad/ship-it-api
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

  nodePort: 30001
  containerPort: 80
  servicePort: 80

operator:
  image:
    repository: wattpad/ship-it-operator
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 256Mi

  gracePeriod: 10s
  metricsPort: 8080
  enableLeaderElection: false
  targetNamespace: "default"

syncd:
  annotations: {}

  image:
    repository: wattpad/ship-it-syncd
    tag: latest
    pullPolicy: IfNotPresent

  ecrQueue: ship-it-ecr.fifo
  githubQueue: ship-it-github.fifo

  githubOrg: ""
  operationsRepository: ""

  releaseName: ship-it-registry
  releaseBranch: master
  registryChartPath: ""

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
