language: go

go:
  - 1.13

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: Test and Lint
    if: type = pull_request
  - name: Build
    if: type = pull_request
  - name: Push
    if: type = push AND branch = master
  - name: Codecov
    if: type = pull_request

jobs:
  include:
    - stage: Build
      name: Docker
      script:
        - TARGET=ship-it-api make build
        - TARGET=ship-it-syncd make build
    
    - stage: Build
      name: Operator
      before_script:
        - cd operator
      script:
        - make docker-build

    - stage: Test and Lint
      name: Go
      install: GO111MODULE=off go get "github.com/golangci/golangci-lint/cmd/golangci-lint"
      script:
        - golangci-lint --deadline=5m run -D errcheck -E goimports -E interfacer -E scopelint ./...
        - go test ./...

    - stage: Test and Lint
      name: Operator
      before_script:
        - curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.8/kubebuilder_1.0.8_linux_amd64.tar.gz | tar -xz -C /tmp/
        - sudo mv /tmp/kubebuilder_1.0.8_linux_amd64 /usr/local/kubebuilder
        - export PATH=$PATH:/usr/local/kubebuilder/bin
        - cd operator
      script:
        - make test

    - stage: Test and Lint
      name: JavaScript
      script: cd web && npm install -D && npm run lint && npm run test

    - stage: Test and Lint
      name: Helm Lint
      script:
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod 700 get_helm.sh && sudo ./get_helm.sh
        - helm init --client-only
        - helm lint deploy/ship-it
        - helm lint deploy/localstack

    - stage: Push
      name: Push
      install: pip install --user awscli
      before_script:
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
      script:
        - TARGET=ship-it-api make push
        - TARGET=ship-it-syncd make push
        - cd operator && make docker-push

    - stage: Codecov
      name: Test Coverage Report
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success: bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
