language: go

go:
  - 1.12.1

env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: Test
    if: type = pull_request
  - name: Push
    if: type = push AND branch = master

jobs:
  include:
    - stage: Test
      name: Lint
      install: go get "honnef.co/go/tools/cmd/staticcheck"
      script:
        - go vet ./...
        - staticcheck ./...

    - stage: Test
      name: Test
      script: go test ./...

    - stage: Push
      name: Push
      before_install:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
      script: make push

branches:
  only:
    - master
