language: go

go:
  - 1.12.1

env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: Test
    if: type = pull_request
  - name: Build
    if: type = pull_request
  - name: Push
    if: type = push AND branch = master

jobs:
  include:
    - stage: Build
      name: Docker
      script: make build

    - stage: Test
      name: GoLint
      install: go get "github.com/golangci/golangci-lint/cmd/golangci-lint"
      script: golangci-lint run -E goimports -E interfacer ./...
    
    - stage: Test
      name: JSLint
      script: cd web && npm install -D && npm run lint

    - stage: Test
      name: Test
      script: go test ./...

    - stage: Push
      name: Push
      install: pip install --user awscli
      before_script:
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
      script: make push

branches:
  only:
    - master
