language: go

go:
  - 1.12.1
  - tip

env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: Test
    if: type = pull_request
  - name: Build
    if: type = pull_request
  - name: Push
    if: type = push AND branch = master
  - name: Codecov
    if: type = pull_request

jobs:
  include:
    - stage: Build
      name: Docker
      script:
        - TARGET=ship-it-api make build
        - TARGET=ship-it-ecrconsumer make build

    - stage: Test
      name: Go
      install: go get "github.com/golangci/golangci-lint/cmd/golangci-lint"
      script: 
        - golangci-lint run -D errcheck -E goimports -E interfacer ./...
        - go test ./...
    
    - stage: Test
      name: JavaScript
      script: cd web && npm install -D && npm run lint && npm run test

    - stage: Push
      name: Push
      install: pip install --user awscli
      before_script:
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
      script:
        - TARGET=ship-it-api make push
        - TARGET=ship-it-ecrconsumer make push

    - stage: Codecov
      name: Test Coverage Report
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success: bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
