apiVersion: helmreleases.k8s.wattpad.com/v1alpha1
kind: HelmRelease
metadata:
  name: example-microservice
spec:
  releaseName: example-release

  chart:
    repository: wattpad.s3.amazonaws.com/helm-charts
    path: microservice
    revision: HEAD

  values:
    image:
      repository: dkr.ecr.amazonaws.com/foo
      tag: foo

    iamRoleName: foo
    serviceAccountName: foo

    autoscaler:
      minPods: 1
      maxPods: 2
      targetCPUUtilizationPercent: 80
