apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ship-it-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - hostPort: 31901
        containerPort: 31901
  - role: worker
  - role: worker
