apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmrelease.k8s.wattpad.com
spec:
  group: k8s.wattpad.com
  scope: Namespaced
  version: v1alpha1
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
    shortNames:
      - rls
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            releaseName:
              type: string
            chart:
              type: object
              properties:
                repository:
                  type: string
                path:
                  type: string
                revision:
                  type: string
            values:
              type: object
              additionalProperties: true
