apiVersion: v1
kind: Service
metadata:
  name: {{ template "ship-it.fullname" . }}-api
  labels:
    {{ include "ship-it.metadataLabels" . | nindent 2 | trim}}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.api.servicePort }}
      nodePort: {{ .Values.api.nodePort }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "ship-it.name" . }}
    instance: {{ .Release.Name }}
    role: api
