apiVersion: v1
kind: Service
metadata:
  name: {{ include "ship-it.fullname" . }}
  labels:
    {{ include "ship-it.labels" . | nindent 4 | trim }}
spec:
  {{ with .Values.api.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      nodePort: {{ .nodePort }}
  {{- end }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "ship-it.name" . }}-api
    instance: {{ .Release.Name }}
