apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ship-it.fullname" . }}
  labels:
    {{ include "ship-it.metadataLabels" . | nindent 2 | trim }}
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - shipit.wattpad.com
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
