{{- if .Values.externalSecretName }}
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ .Values.existingSecretName }}
  labels:
    {{ include "ship-it.metadataLabels" . | nindent 2 | trim }}
spec:
  backendType: secretsManager
  dataFrom:
  - {{ .Values.externalSecretName }}
{{- end }}
