{{- if .Values.externalSecretName }}
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ .Values.existingSecretName }}
spec:
  backendType: secretsManager
  dataFrom:
  - {{ .Values.externalSecretName }}
{{- end }}
