apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ship-it.fullname" . }}
  labels:
    {{include "ship-it.metadataLabels" . | nindent 2 | trim }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleArn }}
