apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ship-it.fullname" . }}-syncd
  annotations:
    {{ toYaml .Values.syncd.annotations | nindent 2 | trim }}
  labels:
    {{ include "ship-it.metadataLabels" . | nindent 2 | trim }}
spec:
  selector:
    matchLabels:
      app: {{ template "ship-it.name" . }}
      instance: {{ .Release.Name }}
      role: syncd
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: {{ template "ship-it.name" . }}
      labels:
        {{ include "ship-it.metadataLabels" . | nindent 6 | trim }}
        role: syncd
    spec:
      serviceAccountName: {{ template "ship-it.fullname" . }}
      containers:
        - name: {{ template "ship-it.fullname" . }}-syncd
          image: {{ include "ship-it.syncd.image" . }}
          imagePullPolicy: {{ .Values.syncd.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecretName }}
                optional: false
          env:
            - name: AWS_REGION
              value: {{ .Values.awsRegion }}
            - name: REGISTRY_CHART_PATH
              value: {{ .Values.syncd.registryChartPath }}
            - name: RELEASE_NAME
              value: {{ .Values.syncd.releaseName }}
            - name: OPERATIONS_REPOSITORY
              value: {{ .Values.syncd.operationsRepository }}
            - name: ECR_QUEUE
              value: {{ .Values.syncd.ecrQueue }}
            - name: GITHUB_QUEUE
              value: {{ .Values.syncd.githubQueue }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: RELEASE_BRANCH
              value: {{ .Values.syncd.releaseBranch }}
            - name: TILLER_HOST
              value: {{ .Values.tillerAddress }}
            - name: GITHUB_ORG
              value: {{ .Values.syncd.githubOrg }}
          {{- if .Values.useDogstatsdHostIP }}
            - name: DOGSTATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- end }}
          {{- range $name, $value := .Values.devEnv }}
            - name: {{ $name }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            {{ toYaml .Values.syncd.resources | nindent 12 | trim }}
          volumeMounts:
            - mountPath: {{ .Values.sslCertPath }}
              name: aws-cert
      volumes:
        - name: aws-cert
          hostPath:
            path: {{ .Values.sslCertPath }}
