---
apiVersion: shipit.wattpad.com/v1beta1
kind: HelmRelease
metadata:
  name: example-microservice
  annotations:
    helmreleases.shipit.wattpad.com/autodeploy: "true"
    helmreleases.shipit.wattpad.com/code: "https://github.com/Wattpad/highlander/tree/master/wattpad/src/services/foo"
    helmreleases.shipit.wattpad.com/datadog: "https://app.datadoghq.com/dashboard/a8k-ro2zk-k8a"
    helmreleases.shipit.wattpad.com/slack: "#squad-velocity"
    helmreleases.shipit.wattpad.com/squad: velocity
    helmreleases.shipit.wattpad.com/sumologic: "https://service.us2.sumologic.com/ui/#/search/ufB9zZJ5iFYRyHOMkJwMvZW7lu32v5xHOYNLURhf"
spec:
  releaseName: example-release

  chart:
    repository: s3://charts.wattpadhq.com
    path: microservice
    revision: HEAD

  values:
    image:
      repository: dkr.ecr.amazonaws.com/foo
      tag: foo

    iamRoleName: foo
    serviceAccountName: foo

    autoscaler:
      minPods: 1
      maxPods: 2
      targetCPUUtilizationPercent: 80
